### ISSUE TITLE
document build and run procedure on Windows

### ISSUE THREAD

**Issue by arjenmarkus** [akohlmey/tclmpi#25]
Building the extension on Windows and running the examples is a bit different from Linux:
- You need to install an appropriate implementation of MPI
- The various libraries you use must be compatible
- Use MinGW or MSYS? (What if you use Wine for cross-building?)
- When running, the path may need to be set

This requires some changes to the Makefile and running your programs may need
some preparations. Nothing really complicated, but there are enough details to take
care of, such that a "read me" file would come in handy

**Comment by akohlmey** [comment]
With switching to CMake and pre-processing of the Tcl files to properly insert version number and name of the shared object. This is more automatic. CMake will still need to be told where to find the MPI and Tcl headers and libs, if it cannot find them automatically. Added a few more details on how to use auto_path in Tcl scripts or setting the environment variable TCLLIBPATH to have Tcl find the package.
